const Data = [
    {
      id: 1,
      category: "Post Graduation",
      icon: "icon-graduation",
      year: "2024 - 2026",
      title: "M.Tech",
      desc: "IIT Guwahati",
    },
    {
      id: 2,
      category: "Post Graduation",
      icon: "icon-badge",
      year: "GPA - 8.93",
      title: "Specialization",
      desc: "Artificial Intelligence",
    },
    {
      id: 3,
      category: "Graduation",
      icon: "icon-graduation",
      year: "2020 - 2024",
      title: "B.Tech",
      desc: "Dr. A.P.J Abdul Kalam Technical University",
    },
    {
      id: 4,
      category: "Graduation",
      icon: "icon-badge",
      year: "GPA - 8.11",
      title: "Specialization",
      desc: "Computer Science Engineering",
    },
    {
      id: 5,
      category: "Intermediate",
      icon: "icon-graduation",
      year: "2018 - 2019",
      title: "Intermediate",
      desc: "St. Paul's Inter College",
    },
    {
      id: 6,
      category: "Intermediate",
      icon: "icon-badge",
      year: "GPA - 8.2",
      title: "Specialization ",
      desc: "Science",
    },
    {
      id: 7,
      category: "Highschool",
      icon: "icon-graduation",
      year: "2016 - 2017",
      title: "High School",
      desc: "St. Paul's Inter College",
    },
    {
      id: 8,
      category: "Highschool",
      icon: "icon-badge",
      year: "GPA - 8.17",
      title: "Specialization ",
      desc: "Science",
    },
  ];

  export default Data;